"""add overdraft limit to account

Revision ID: 621a5b42c0f5
Revises: af8d553fd4c9
Create Date: 2026-02-09 13:24:56.807314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621a5b42c0f5'
down_revision: Union[str, Sequence[str], None] = 'af8d553fd4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('overdraft_limit', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'overdraft_limit')
    # ### end Alembic commands ###
