"""add customer-scoped idempotency to transactions

Revision ID: 66eb711e5008
Revises: 621a5b42c0f5
Create Date: 2026-02-09 17:20:52.908558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66eb711e5008'
down_revision: Union[str, Sequence[str], None] = '621a5b42c0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('customer_id', sa.UUID(), nullable=False))
    op.alter_column('transactions', 'idempotency_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(op.f('transactions_idempotency_key_key'), 'transactions', type_='unique')
    op.create_unique_constraint('uq_customer_idempotency', 'transactions', ['customer_id', 'idempotency_key'])
    op.create_foreign_key(None, 'transactions', 'customers', ['customer_id'], ['customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint('uq_customer_idempotency', 'transactions', type_='unique')
    op.create_unique_constraint(op.f('transactions_idempotency_key_key'), 'transactions', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('transactions', 'idempotency_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('transactions', 'customer_id')
    # ### end Alembic commands ###
